#!/bin/bash
# pass commit quote as an argument
# For example:
# . commit "this is a commit description string"
#
# copy the contents of the private directory to another, git controlled, directory
#
# we use rsync so we can exclude the git directory; which will screw things up as there is already one there
#
rsync -av ~/linuxprojects/pysystemtrade-me/private/ ~/private/pysystemtrade-me --exclude .git
#
# git add/commit/push cycle on the main pysystemtrade directory
#
cd ~/linuxprojects/pysystemtrade-me
git add *
git commit -m "$1"
git push
#
# git add/commit/push cycle on the copied private directory
#
cd ~/private/
git add *
git commit -m "$1"
git push

