name: Slow test (develop)

on:
  schedule:
    - cron: '0 2 * * *'

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.10.13 ]

    steps:

    - uses: actions/checkout@v4
      with:
        ref: "develop"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install pip setuptools wheel
        pip install pytest
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest --runslow  --disable-warnings

    #- name: Coverage report
    #  run: |
    #    coverage html
